// Generated by php-wasm-compiler's `compile/cli.mjs compile-extension`
// (CLAUDE.md decision 42/46) — do not hand-edit, it's regenerated on every build.

export interface RegisteredPHPExtension {
	/** The extension's bare name, e.g. "sodium" (matches manifest.json's own "name"). */
	name: string;
	/** Absolute path to the compiled .so on disk. */
	soPath: string;
	/** Extra php.ini `key=value` lines to write after the `extension=` line, if any. */
	iniEntries?: Record<string, string>;
}

/**
 * Resolves every extension artifact this package ships for `phpVersion`
 * (major.minor, e.g. "8.5"), in the order they must be loaded.
 */
export default function register(phpVersion: string): RegisteredPHPExtension[];
