// Generated by php-wasm-compiler's `compile/cli.mjs compile-extension`
// (CLAUDE.md decision 42) — do not hand-edit, it's regenerated on every build.
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { resolvePHPExtension } from '@php-wasm/universal';

const packageDir = path.dirname(fileURLToPath(import.meta.url));
const manifestNames = ["manifest.json"];

/**
 * Resolves every extension artifact this package ships for `phpVersion`
 * (major.minor, e.g. "8.5"), in the order they must be loaded. Feed the
 * result straight into @php-wasm/universal's withResolvedPHPExtensions().
 */
export default async function register(phpVersion) {
	const resolved = [];
	for (const manifestName of manifestNames) {
		const manifest = JSON.parse(readFileSync(path.join(packageDir, manifestName), 'utf8'));
		const artifact = manifest.artifacts.find((a) => a.phpVersion === phpVersion);
		if (!artifact) {
			throw new Error(`${manifest.name}: no artifact for PHP ${phpVersion} in ${manifestName}.`);
		}
		const bytes = readFileSync(path.join(packageDir, artifact.sourcePath));
		resolved.push(await resolvePHPExtension({ name: manifest.name, source: { format: 'so', bytes } }));
	}
	return resolved;
}
