// Generated by php-wasm-compiler's `compile/cli.mjs compile-extension`
// (CLAUDE.md decision 42) — do not hand-edit, it's regenerated on every build.
import type { ResolvedPHPExtension } from '@php-wasm/universal';

/**
 * Resolves every extension artifact this package ships for `phpVersion`
 * (major.minor, e.g. "8.5"), in the order they must be loaded. Feed the
 * result straight into @php-wasm/universal's withResolvedPHPExtensions().
 */
export default function register(phpVersion: string): Promise<ResolvedPHPExtension[]>;
