// Generated by php-wasm-compiler's `compile/cli.mjs compile-extension`
// (CLAUDE.md decision 42/46) — do not hand-edit, it's regenerated on every build.
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const packageDir = path.dirname(fileURLToPath(import.meta.url));
const manifestNames = ["manifest-mysqlnd.json","manifest.json"];

/**
 * Resolves every extension artifact this package ships for `phpVersion`
 * (major.minor, e.g. "8.5"), in the order they must be loaded. Each entry's
 * `soPath` is an absolute path to the compiled `.so` on disk — the caller
 * (@kirigami/php-wasm) reads its bytes, copies it into its own VM FS, and
 * writes the matching `php.ini` `extension=` directive itself, followed by
 * one `key=value` line per `iniEntries` entry when there are any.
 */
export default function register(phpVersion) {
	return manifestNames.map((manifestName) => {
		const manifest = JSON.parse(readFileSync(path.join(packageDir, manifestName), 'utf8'));
		const artifact = manifest.artifacts.find((a) => a.phpVersion === phpVersion);
		if (!artifact) {
			throw new Error(`${manifest.name}: no artifact for PHP ${phpVersion} in ${manifestName}.`);
		}
		const entry = { name: manifest.name, soPath: path.join(packageDir, artifact.sourcePath) };
		if (manifest.iniEntries) entry.iniEntries = manifest.iniEntries;
		return entry;
	});
}
